package com.example.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "STUDENT".
 */
@Entity
public class Student {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private float height;

    @Generated
    public Student() {
    }

    public Student(String name, float height) {
        this.name = name;
        this.height = height;
    }

    public Student(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", height=" + height +
                '}';
    }

    @Generated
    public Student(Long id, String name, float height) {
        this.id = id;
        this.name = name;
        this.height = height;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public float getHeight() {
        return height;
    }

    public void setHeight(float height) {
        this.height = height;
    }

}
